package exceptions;

class Testtwo2{//arithmetic exception
	public static void main(String[] args){
	System.out.println("good morning");
	try{
	System.out.println(10/0);
	}
	catch(Exception e){
		
	}
	System.out.println("good night");
	}
}